version: '3.4'

services:
  dashboard:
    container_name: mhpdt-calibration-dashboard
    image: mhpdt-dashboard
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - AZURE_FUNC_URL=http://azure-functions-local:80
      - DASH_DEBUG_MODE=False
      - DASH_HOST=0.0.0.0
      - DASH_PORT=8050
    ports:
        - "8050:8050"
    depends_on: 
      - azure-functions-local
  
  azure-functions-local:
    container_name: azure-functions-dash
    image: azure-functions-dash-local-env
    build:
      context: .
      dockerfile: ./MHPDT_cross_validation/Dockerfile